CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() ON DELETE CASCADE,
  name TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE TABLE entities (
  user_id uuid REFERENCES users ON DELETE CASCADE, 
  entity_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  trade TEXT,

  PRIMARY KEY (user_id, entity_id)
);

CREATE TABLE entities_franchises (
  user_id uuid REFERENCES users ON DELETE CASCADE,
  entity_id INTEGER,
  
  franchise_id INTEGER GENERATED BY DEFAULT AS IDENTITY,

  address TEXT NOT NULL,

  FOREIGN KEY (user_id, entity_id) REFERENCES entities (user_id, entity_id),
  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE OR REPLACE FUNCTION create_special()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO entities (user_id, name)
  VALUES (NEW.id, NEW.name, NEW.name);
  INSERT INTO entities_franchises (user_id, entity_id)
  VALUES (NEW.id, 1);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER insert_special_user_entity
AFTER INSERT ON users
FOR EACH ROW
EXECUTE create_special();

CREATE INDEX entities_franchises_idx ON entities_franchises(user_id);

CREATE TYPE entity_kind AS ENUM (
  'client', 'supplier', 'service_provider'
);

CREATE TABLE outsourced_entity_franchise_types (
  user_id uuid REFERENCES users ON DELETE CASCADE,
  entity_id INTEGER,
  franchise_id INTEGER,
  type entity_kind

  FOREIGN KEY (user_id, entity_id, franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, entity_id, franchise_id, type)
);

CREATE TABLE items (
  user_id uuid REFERENCES users ON DELETE CASCADE, 
  item_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  description TEXT,

  PRIMARY KEY (user_id, item_id)
);

CREATE INDEX items_idx ON items(user_id);

CREATE TABLE item_categories (
  user_id uuid REFERENCES users ON DELETE CASCADE, 
  category_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  description TEXT,

  PRIMARY KEY (user_id, category_id)
);

CREATE TABLE categories_of_items (
  item_user_id uuid,
  item_id INTEGER,

  category_user_id uuid,
  category_id INTEGER,

  FOREIGN KEY (item_user_id, item_id) REFERENCES items (user_id, item_id),
  FOREIGN KEY (category_user_id, category_id) REFERENCES item_categories (user_id, category_id),
  PRIMARY KEY (item_user_id, item_id, category_user_id, category_id)
);

CREATE TABLE item_units (
  user_id uuid REFERENCES users ON DELETE CASCADE, 
  name TEXT,

  description TEXT,
  wikipedia_url TEXT,

  PRIMARY KEY (user_id, name)
);

CREATE TABLE items_unit_price_history (
  user_id uuid REFERENCES users ON DELETE CASCADE,
  item_id INTEGER,

  history_id INTEGER GENERATED ALWAYS AS IDENTITY,

  unit_user_id uuid NOT NULL,
  unit_name TEXT NOT NULL,

  price_cents INTEGER NOT NULL,
  priced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (user_id, item_id) REFERENCES items (user_id, item_id),
  FOREIGN KEY (unit_user_id, unit_name) REFERENCES item_units (user_id, name),
  PRIMARY KEY (user_id, item_id, history_id)
);

CREATE TABLE operations (
  user_id uuid REFERENCES users ON DELETE CASCADE,
  operation_id INTEGER GENERATED ALWAYS AS IDENTITY,
  
  item_user_id uuid NOT NULL,
  item_id INTEGER NOT NULL,

  unit_price_user_id uuid NOT NULL,
  unit_price_item_id INTEGER NOT NULL,
  unit_price_id INTEGER NOT NULL,

  quantity NUMERIC NOT NULL,

  addressee_user_id uuid NOT NULL,
  addressee_entity_id INTEGER NOT NULL,
  addressee_franchise_id INTEGER NOT NULL,

  sendee_user_id uuid NOT NULL,
  sendee_entity_id INTEGER NOT NULL,
  sendee_franchise_id INTEGER NOT NULL,

  shipped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  arrived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_item_id, item_id) REFERENCES items (user_id, item_id),
  FOREIGN KEY (unit_price_user_id, unit_price_item_id, unit_price_id) REFERENCES items_unit_price_history,
  FOREIGN KEY (adressee_user_id, adressee_entity_id, adressee_franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  FOREIGN KEY (sendee_user_id, sendee_entity_id, sendee_franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, operation_id)
);

CREATE INDEX operations_idx ON operations(user_id);