CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  name TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE TABLE entities (
  user_id uuid REFERENCES users,
  entity_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  trade TEXT,

  PRIMARY KEY (user_id, entity_id)
);

CREATE TABLE entities_franchises (
  user_id uuid,
  entity_id INTEGER,
  
  franchise_id INTEGER GENERATED BY DEFAULT AS IDENTITY,

  address TEXT NOT NULL,

  FOREIGN KEY (user_id, entity_id) REFERENCES entities (user_id, entity_id),
  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE INDEX entities_franchises_idx ON entities_franchises(user_id);

CREATE TABLE outsourced_client_entity_franchises (
  user_id uuid,
  entity_id INTEGER,
  franchise_id INTEGER,

  FOREIGN KEY (user_id, entity_id, franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE TABLE outsourced_supplier_entity_franchises (
  user_id uuid,
  entity_id INTEGER,
  franchise_id INTEGER,

  FOREIGN KEY (user_id, entity_id, franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE TABLE outsourced_service_provider_entity_franchises (
  user_id uuid,
  entity_id INTEGER,
  franchise_id INTEGER,

  FOREIGN KEY (user_id, entity_id, franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE TABLE storage_areas (
  user_id uuid,
  entity_id INTEGER,
  franchise_id INTEGER,

  storage_id INTEGER GENERATED ALWAYS AS IDENTITY,

  description TEXT NOT NULL,
  location_reference TEXT NOT NULL,
  address TEXT,

  FOREIGN KEY (user_id, entity_id, franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, entity_id, franchise_id, storage_id)
);

CREATE TABLE items (
  user_id uuid REFERENCES users,
  item_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  description TEXT,

  PRIMARY KEY (user_id, item_id)
);

CREATE INDEX items_idx ON items(user_id);

CREATE TABLE item_categories (
  user_id uuid REFERENCES users,
  category_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  description TEXT,

  PRIMARY KEY (user_id, category_id)
);

CREATE TABLE categories_of_items (
  item_user_id uuid,
  item_id INTEGER,

  category_user_id uuid,
  category_id INTEGER,

  FOREIGN KEY (item_user_id, item_id) REFERENCES items (user_id, item_id),
  FOREIGN KEY (category_user_id, category_id) REFERENCES item_categories (user_id, category_id),
  PRIMARY KEY (item_user_id, item_id, category_user_id, category_id)
);

CREATE TABLE item_units (
  user_id uuid REFERENCES users,
  unit_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL UNIQUE,
  description TEXT,
  wikipedia_url TEXT,

  PRIMARY KEY (user_id, unit_id)
);

CREATE TABLE items_unit_price_history (
  user_id uuid,
  item_id INTEGER,

  history_id INTEGER GENERATED ALWAYS AS IDENTITY,

  unit_user_id uuid NOT NULL,
  unit_id INTEGER NOT NULL,

  price_cents INTEGER NOT NULL,
  priced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (user_id, item_id) REFERENCES items (user_id, item_id),
  FOREIGN KEY (unit_user_id, unit_id) REFERENCES item_units (user_id, unit_id),
  PRIMARY KEY (user_id, item_id, history_id)
);

CREATE TABLE operations (
  user_id uuid REFERENCES users,
  operation_id INTEGER GENERATED ALWAYS AS IDENTITY,
  
  user_item_id uuid NOT NULL,
  item_id INTEGER NOT NULL,

  unit_price_user_id uuid NOT NULL,
  unit_price_item_id INTEGER NOT NULL,
  unit_price_id INTEGER NOT NULL,

  quantity NUMERIC NOT NULL,

  adressee_user_id uuid NOT NULL,
  adressee_entity_id INTEGER NOT NULL,
  adressee_franchise_id INTEGER NOT NULL,

  sendee_user_id uuid NOT NULL,
  sendee_entity_id INTEGER NOT NULL,
  sendee_franchise_id INTEGER NOT NULL,

  shipped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  arrived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_item_id, item_id) REFERENCES items (user_id, item_id),
  FOREIGN KEY (unit_price_user_id, unit_price_item_id, unit_price_id) REFERENCES items_unit_price_history,
  FOREIGN KEY (adressee_user_id, adressee_entity_id, adressee_franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  FOREIGN KEY (sendee_user_id, sendee_entity_id, sendee_franchise_id) REFERENCES entities_franchises (user_id, entity_id, franchise_id),
  PRIMARY KEY (user_id, operation_id)
);

CREATE INDEX operations_idx ON operations(user_id);