CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  password_hash TEXT NOT NULL
);

CREATE TABLE entities (
  user_id uuid REFERENCES users,
  entity_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  trade TEXT,

  PRIMARY KEY (user_id, entity_id)
);

CREATE TABLE entities_franchises (
  user_id uuid REFERENCES users,
  entity_id INTEGER REFERENCES entities,
  franchise_id INTEGER GENERATED BY DEFAULT AS IDENTITY,

  address TEXT NOT NULL,

  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE INDEX entities_franchises_idx ON entities_franchises(user_id);

CREATE TABLE outsourced_client_entities (
  user_id uuid REFERENCES users,
  entity_id INTEGER REFERENCES entities,
  franchise_id INTEGER REFERENCES entities_franchises,

  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE TABLE outsourced_supplier_entities (
  user_id uuid REFERENCES users,
  entity_id INTEGER REFERENCES entities,
  franchise_id INTEGER REFERENCES entities_franchises,

  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE TABLE outsourced_service_provider_entities (
  user_id uuid REFERENCES users,
  entity_id INTEGER REFERENCES entities,
  franchise_id INTEGER REFERENCES entities_franchises,

  PRIMARY KEY (user_id, entity_id, franchise_id)
);

CREATE TABLE storage_areas (
  user_id uuid REFERENCES users,
  entity_id INTEGER REFERENCES entities,
  franchise_id INTEGER REFERENCES entities_franchises,
  storage_id INTEGER GENERATED ALWAYS AS IDENTITY,

  description TEXT NOT NULL,
  location_reference TEXT NOT NULL,
  address TEXT,

  PRIMARY KEY (user_id, entity_id, franchise_id, storage_id)
);

CREATE TABLE items (
  user_id uuid REFERENCES users,
  item_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  description TEXT,

  PRIMARY KEY (user_id, item_id)
);

CREATE INDEX items_idx ON items(user_id);

CREATE TABLE item_categories (
  user_id uuid REFERENCES users,
  category_id INTEGER GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL,
  description TEXT,

  PRIMARY KEY (user_id, category_id)
);

CREATE TABLE categories_of_items (
  user_id uuid REFERENCES users,
  item_id INTEGER REFERENCES items,
  category_id INTEGER REFERENCES item_category,

  PRIMARY KEY (user_id, item_id, category_id)
);

CREATE TABLE item_units (
  user_id uuid REFERENCES users,
  unit_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

  name TEXT NOT NULL UNIQUE,
  description TEXT,
  wikipedia_url TEXT,

  PRIMARY KEY (user_id, unit_id)
);

CREATE TABLE items_unit_price_history (
  user_id uuid REFERENCES users,
  item_id INTEGER REFERENCES items,
  history_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

  unit_id INTEGER REFERENCES units NOT NULL,
  price_cents INTEGER NOT NULL,
  priced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  PRIMARY KEY (user_id, item_id, history_id)
);

CREATE TABLE operations (
  user_id uuid REFERENCES users,
  operation_id INTEGER GENERATED ALWAYS AS IDENTITY,
  
  item_id REFERENCES items NOT NULL,
  unit_price_id INTEGER REFERENCES items_unit_price_history NOT NULL,
  quantity NUMERIC NOT NULL,
  addressee_id INTEGER REFERENCES entity NOT NULL,
  sendee_id INTEGER REFERENCES entity NOT NULL,
  shipped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  arrived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (user_id, operation_id)
);

CREATE INDEX operations_idx ON operations(user_id);